/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import java.util.Calendar;
import java.util.Date;
import controllers.StocManagementMain;
import java.awt.Cursor;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author ioapau
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLHome = new javax.swing.JLabel();
        jLBy = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFisier = new javax.swing.JMenu();
        jMIProduse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIIesire = new javax.swing.JMenuItem();
        jMenuOperatii = new javax.swing.JMenu();
        jMIIntrari = new javax.swing.JMenuItem();
        jMIIesiri = new javax.swing.JMenuItem();
        jMenuRapoarte = new javax.swing.JMenu();
        jMITotalIntrari = new javax.swing.JMenuItem();
        jMITotalIesiri = new javax.swing.JMenuItem();
        jSep = new javax.swing.JPopupMenu.Separator();
        jMIStocuriDetaliat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIUpdateRaport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stoc Management");
        setPreferredSize(new java.awt.Dimension(750, 410));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLHome.setFont(new java.awt.Font("Waree", 3, 36)); // NOI18N
        jLHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLHome.setText("Stoc Management");
        jLHome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLHome.setInheritsPopupMenu(false);
        jLHome.setOpaque(true);
        jLHome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLBy.setText("by Priscilla Consulting");

        jMenuFisier.setLabel("Fisier");

        jMIProduse.setText("Produse");
        jMIProduse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProduseActionPerformed(evt);
            }
        });
        jMenuFisier.add(jMIProduse);
        jMenuFisier.add(jSeparator1);

        jMIIesire.setText("Iesire");
        jMIIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIIesireActionPerformed(evt);
            }
        });
        jMenuFisier.add(jMIIesire);

        jMenuBar1.add(jMenuFisier);

        jMenuOperatii.setText("Operatii");

        jMIIntrari.setText("Intrari");
        jMIIntrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIIntrariActionPerformed(evt);
            }
        });
        jMenuOperatii.add(jMIIntrari);

        jMIIesiri.setText("Iesiri");
        jMIIesiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIIesiriActionPerformed(evt);
            }
        });
        jMenuOperatii.add(jMIIesiri);

        jMenuBar1.add(jMenuOperatii);

        jMenuRapoarte.setText("Rapoarte");

        jMITotalIntrari.setText("Raport Zilnic");
        jMITotalIntrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITotalIntrariActionPerformed(evt);
            }
        });
        jMenuRapoarte.add(jMITotalIntrari);

        jMITotalIesiri.setText("Raport Lunar");
        jMITotalIesiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITotalIesiriActionPerformed(evt);
            }
        });
        jMenuRapoarte.add(jMITotalIesiri);
        jMenuRapoarte.add(jSep);

        jMIStocuriDetaliat.setText("Stocuri Detaliat");
        jMIStocuriDetaliat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIStocuriDetaliatActionPerformed(evt);
            }
        });
        jMenuRapoarte.add(jMIStocuriDetaliat);
        jMenuRapoarte.add(jSeparator2);

        jMIUpdateRaport.setText("Actualizare Raport");
        jMIUpdateRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUpdateRaportActionPerformed(evt);
            }
        });
        jMenuRapoarte.add(jMIUpdateRaport);

        jMenuBar1.add(jMenuRapoarte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLHome, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLBy)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jLHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBy)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        int Year = calendar.get(Calendar.YEAR);
        jLBy.setText(String.format("2011 - %d by Priscilla Consulting", Year));
    }//GEN-LAST:event_formWindowOpened

    private void jMIProduseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProduseActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayProduse();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMIProduseActionPerformed

    private void jMIIntrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIIntrariActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayIntrari();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMIIntrariActionPerformed

    private void jMIIesiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIIesiriActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayIesiri();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMIIesiriActionPerformed

    private void jMIIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIIesireActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMIIesireActionPerformed

    private void jMITotalIntrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITotalIntrariActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayReportIODay();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMITotalIntrariActionPerformed

    private void jMITotalIesiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITotalIesiriActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayReportIOMonth();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMITotalIesiriActionPerformed

    private void jMIUpdateRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUpdateRaportActionPerformed
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.updateRaport();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        JOptionPane.showMessageDialog(this, "Raportul a fost actualizat", 
                "Informare", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMIUpdateRaportActionPerformed

    private void jMIStocuriDetaliatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIStocuriDetaliatActionPerformed
        // TODO add your handling code here:
        
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        StocManagementMain controller = StocManagementMain.getInstance();
        controller.displayReportStocuriDetaliat();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMIStocuriDetaliatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBy;
    private javax.swing.JLabel jLHome;
    private javax.swing.JMenuItem jMIIesire;
    private javax.swing.JMenuItem jMIIesiri;
    private javax.swing.JMenuItem jMIIntrari;
    private javax.swing.JMenuItem jMIProduse;
    private javax.swing.JMenuItem jMIStocuriDetaliat;
    private javax.swing.JMenuItem jMITotalIesiri;
    private javax.swing.JMenuItem jMITotalIntrari;
    private javax.swing.JMenuItem jMIUpdateRaport;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFisier;
    private javax.swing.JMenu jMenuOperatii;
    private javax.swing.JMenu jMenuRapoarte;
    private javax.swing.JPopupMenu.Separator jSep;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
