DROP VIEW VLASTSTOCMAPPINGS;

CREATE VIEW VLASTSTOCMAPPINGS AS
SELECT 
    IDPRODUS,
    C.DATA_MONTH AS DATA, 
    MAX(S."DATA") AS PREVDATE
FROM (SELECT DISTINCT DATA_MONTH FROM TCALENDAR) C
JOIN VSTOCENDOFMONTH S
ON C.DATA_MONTH >= S.DATA_MONTH
GROUP BY C.DATA_MONTH, IDPRODUS;
