SELECT 
SUBSTR(CAST(Data AS VARCHAR(10)), 1, 7) || '-' ||
CAST(MAX(CAST(SUBSTR(CAST(Data AS VARCHAR(10)), 9, 2) AS INT)) AS CHAR(2)) AS LASTDAY
FROM TCALENDAR
GROUP BY SUBSTR(CAST(Data AS VARCHAR(10)), 1, 7)