SELECT DATA, IDPRODUS, DENUMIRE, UM, 
    SUM(PRETINTRARE) AS PRETINTRARE, SUM(PRETIESIRE) AS PRETIESIRE,
    SUM(CANTITATEINTRARE) AS CANTITATEINTRARE, SUM(CANTITATEIESIRE) AS CANTITATEIESIRE
FROM 
(
SELECT I.Data, I.IDProdus, I.Denumire, I.UM,I.PretIntrare,I.CantitateIntrare,
    CASE WHEN O.PretIesire IS NULL THEN 0 ELSE O.PretIesire END AS PretIesire,
    CASE WHEN O.CantitateIesire IS NULL THEN 0 ELSE O.CantitateIesire END AS CantitateIesire
FROM VRAPORTINDAY I
LEFT JOIN VRAPORTOUTDAY O ON I.Data=O.Data AND I.IDProdus=O.IDProdus

UNION 

SELECT O.Data, O.IDProdus, O.Denumire, O.UM,
    CASE WHEN I.PretIntrare IS NULL THEN 0 ELSE I.PretIntrare END AS PretIntrare,
    CASE WHEN I.CantitateIntrare IS NULL THEN 0 ELSE I.CantitateIntrare END AS CantitateIntrare,
    O.PretIesire,O.CantitateIesire
FROM VRAPORTOUTDAY O
LEFT JOIN VRAPORTINDAY I ON O.Data=I.Data AND O.IDProdus=I.IDProdus
) S
GROUP BY DATA, IDPRODUS, DENUMIRE, UM
ORDER BY Data DESC, Denumire
