SELECT SUBSTR(CAST(Data AS VARCHAR(10)), 1, 7) AS DATA,IDPRODUS, DENUMIRE, UM, 
    SUM(PRETINTRARE) AS PRETINTRARE,SUM(PRETIESIRE) AS PRETIESIRE,
    SUM(CANTITATEINTRARE) AS CANTITATEINTRARE,SUM(CANTITATEIESIRE) AS CANTITATEIESIRE
FROM VRAPORTIODAY
GROUP BY SUBSTR(CAST(Data AS VARCHAR(10)), 1, 7), IDProdus, Denumire, UM
