SELECT C.DATA,P.ID,P.DENUMIRE,P.UM,P.CATEGORIE, 
CASE WHEN CI.CantitateIntrare IS NULL THEN 0 ELSE CI.CantitateIntrare END
-
CASE WHEN CO.CantitateIesire IS NULL THEN 0 ELSE CO.CantitateIesire END AS Stoc
FROM TPRODUSE P 
JOIN TCALENDAR C ON TRUE
LEFT JOIN (
    SELECT C.DATA,I.IDPRODUS,
    SUM(CASE WHEN I.CANTITATE IS NULL THEN 0 ELSE I.CANTITATE END) AS CantitateIntrare
    FROM TCALENDAR C
    JOIN TPRODUSE P ON TRUE
    JOIN VINTRARI I ON C.DATA>=I.DATA AND I.IDPRODUS=P.ID
    GROUP BY C.DATA, I.IDPRODUS
) CI ON P.ID=CI.IDPRODUS AND C.DATA=CI.DATA
LEFT JOIN (
    SELECT C.DATA,O.IDPRODUS,
    SUM(CASE WHEN O.CANTITATE IS NULL THEN 0 ELSE O.CANTITATE END) AS CantitateIesire
    FROM TCALENDAR C
    JOIN TPRODUSE P ON TRUE
    JOIN VIESIRI O ON C.DATA>=O.DATA AND O.IDPRODUS=P.ID
    GROUP BY C.DATA, O.IDPRODUS
) CO ON P.ID=CO.IDPRODUS AND C.DATA=CO.DATA
ORDER BY C.DATA DESC