DROP VIEW VSTOCENDOFMONTH;

CREATE VIEW VSTOCENDOFMONTH AS
SELECT R1.DATA AS DATA, R1.DATA_MONTH, R1.IDPRODUS, R1.STOC
FROM VRAPORTTOTALDAY R1
JOIN (SELECT MAX("DATA") AS "DATA", DATA_MONTH, IDPRODUS 
      FROM VRAPORTTOTALDAY
      GROUP BY IDPRODUS, DATA_MONTH
     ) R2
ON R1.IDPRODUS=R2.IDPRODUS and R1.DATA=R2.DATA;
